destinations = [
"Agnew, Thomas",
"Alspach, Crystal",
"Argot, Tina",
"Auditorium",
"Borger, Dickson",
"Boys Locker Rm. Office/R.Reinhart",
"Brantlecht, Karen",
"Brennan, Karen",
"Brown, Justin",
"Bucheit, Cheryl",
"Bucheit, Leon",
"Buggy, Damian",
"Cafeteria 1",
"Cafeteria 2",
"Calderone, Brian",
"Cinicola, Michelle",
"Clemas, Jaime",
"Deitz, Heather",
"Dommel, Rebecca",
"Dowd, Angela",
"Eshbach, Mary Elizabeth",
"Farina, Melissa",
"Gaul, Brett",
"Geske, Morgan",
"Girls Locker Room Office",
"Glassic, Ed",
"Haegele, Stephen",
"Hardick, Andrea",
"Hartranft, Tyler",
"Heckman, Andrea",
"Herber, Tracy",
"Herman, Ann",
"Hetrich, Benjamin",
"IT/Tech Team",
"Jackson, Sara",
"Keck, Teresa",
"Kelly, Donine",
"King, Greg",
"King, Katherine",
"Kline, David",
"Kline, Megan",
"Large Group Instruction (LGI)",
"Laughlin, Terence",
"Library",
"Long, Barbara",
"Lowe, Cory",
"McBreen, Nicholas",
"McCarthy-Wright, Teresa",
"Menapace, Aaron",
"Mennig, Karen",
"Ottaviani, Doreen",
"Palerino, Stephanie",
"Personal Fitness Room",
"Ponter, Mindy",
"Reinard, Oksana",
"Reinhart, Richard",
"Reppert, Turie",
"Resource Room",
"Shefter, David",
"Sinopoli, Katie",
"Stauffer, Brittany",
"Stevens, Brynell",
"Stump-Dalton, Korinne",
"Temporary Learning Placement (TLP)",
"Texter, Mary",
"Training Room",
"Trubilla, Nicole",
"TV Studio",
"Virtual Learning Room",
"Weiss, Patricia",
"Welgo, Lisa",
"Wellness Classroom",
"Zimmerman, Clark"]

